name: Python application  
  
on:  
  push:  
    branches: [master]  
  pull_request:  
    branches: [master]  
  
permissions:  
  contents: read  
  
jobs:  
  build:  
  
    runs-on: ubuntu-latest  
  
    steps:  
    - uses: actions/checkout@v3  
    - name: Set up Python 3.10  
      uses: actions/setup-python@v3  
      with:  
        python-version: "3.10"  
    - name: Install dependencies  
      run: |  
        python -m pip install --upgrade pip  
        pip install -i https://mirrors.aliyun.com/pypi/simple -r requirements.txt  
     - name: Run tests  
      run: python AddUser.py  
      shell: bash  
    - name: Run tests (no input required)  
      run: python AddUser-noinput.py  
      shell: bash  
    - name: Daily job  
      schedule: cron(0 0 * * ?)  
      run: python Main.py  
      shell: bash
